name: on-schedule
run-name: on schedule

on:
  schedule:
    # weekly
    - cron: "0 0 * * 1"

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  update-citations:
    # only run on user instance of template, not template itself
    if: github.repository != 'greenelab/lab-website-template'
    uses: ./.github/workflows/update-citations.yaml
    secrets: inherit
    with:
      open-pr: false

  deploy-site:
    needs: update-citations
    if: |
      needs.update-citations.result == 'success' &&
      (
        needs.update-citations.outputs.changed == 'true' ||
        github.event_name == 'workflow_dispatch'
      )
    uses: ./.github/workflows/jekyll.yml
